os:
- linux
- osx
dist: trusty
sudo: required
language: c
compiler:
- clang
- gcc
script:
- mkdir build && pushd build
- cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Release
- make && make test && make install
- popd && rm -rf build
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/include/chi2comb.h;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libchi2comb.so;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libchi2comb_static.a;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/include/chi2comb.h;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libchi2comb.dylib;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libchi2comb_static.a;
  fi
- bash <(curl -fsSL https://raw.githubusercontent.com/limix/chi2comb/master/install)
after_success:
- mkdir dist && pushd dist && cmake .. -DCMAKE_BUILD_TYPE=Release && popd
- mv dist chi2comb-`cat VERSION`
- tar czf chi2comb-`cat VERSION`.tar.gz chi2comb-`cat VERSION`
- rm -rf dist
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: jecq/zuAXnrPxbwut9OPadrG4B2dSaAh04uJN31xjC7tA9sIEQ7hNofXbHjB1xWcxSON2Bqnm370My7R1/HuIdUa1DZf8imFsJrqBch1uh69sG6aA3h56bnGIV9cPDe/hOcDxFHcqDhjnJRO9r142TdhguexXlk4SpK04Rho2dYD4UosOSusvtKJu+EFW51HMa2ImY7j4cOTiAi95oZPaLj41YiJEVyWnAhV96BKofo2JWghEN9l34sm28V7nT0qNJPJNHbVBUtmzhYI2xa6khrpglB7eV32atQvmAQP7lvTfmhw2ki95C1ClWQa8WaNYlEIn79+NIiL16JM5jPiNXVUyI5ldXonM6e+zv1GmEIEeodPN0DkqeTzixT4sErTVySRhLCBnGxSbkGPivs3COs6e4a+tqvo5LPnCaA22wWcWrn5CqzUK+zcFPwgIuDeEB7H7TfahaQXdc+cn92c/5EczIfZ6emPxjKtnoXvRu53cdA4rNsDkGN9ynZ2DJTwfvPe1fIoSzIjFefrXhQ1bUXhUFsX1Ya5TEBO2i4jdiro3wmqj637W4L3TH3ZLGieiXEPCHe2gjQQwBbuOiNi+XEOPAU1DbuMGjtjXKv+IjuiwOZM/YS/XsXCh8UCas770K8JrHI0xbyAmCEPEdrd4l1wGgFxXeZ1UgzPhLnmRt0=
  on:
    tags: true
    repo: limix/chi2comb
    branch: master
